config/routes.rb
Rails.application.routes.draw do
  get 'calendar/index'
  resources :tickets do
    collection do
      get :users
      get :assigned
      get :created
    end
  end
  root 'core#index'
  devise_for :users
  get 'dashboard', to: "core#dashboard" 
  get 'calendar', to: "calendar#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?
    can [:read, :update, :create, :destroy], Ticket, assigner_id: user.id
    can [:read, :update], Ticket, assignee_id: user.id
    
    can :assigned, Ticket, assignee_id: user.id
    can :created, Ticket, assigner_id: user.id
    can :users, Ticket

    cannot [:read, :update, :destroy], Ticket do |ticket|
      ticket.assigner_id != user.id && ticket.assignee_id != user.id
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    validates :title, presence: true
    belongs_to :assigner, class_name: 'User'
    belongs_to :assignee, class_name: 'User', optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :assigned_tickets, class_name: 'Ticket'
  has_many :created_tickets, class_name:'Ticket' , dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to dashboard_path, alert: exception.message }
    end
  end
private
  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_action :authenticate_user!
  def index
    @meetings = Ticket.where(assignee_id: current_user.id)
  end
end

app/controllers/core_controller.rb
class CoreController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
  end

  def dashboard
    @new_count = Ticket.where(assignee_id: current_user, status: "New").count
    @inprogress_count = Ticket.where(assignee_id: current_user, status: "In Progress").count
    @pending_count = Ticket.where(assignee_id: current_user, status: "Pending").count
    @completed_count = Ticket.where(assignee_id: current_user, status: "Completed").count
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
    @assignee_email = User.find(@ticket.assignee_id).email
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.assignee_id ||= current_user.id if @ticket.assignee_id.nil?

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.assigner_id == current_user.id
        if @ticket.update(ticket_params)
          format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
          format.json { render :show, status: :ok, location: @ticket }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      else
        # Only update the status
        if @ticket.update(status: params[:ticket][:status])
          format.html { redirect_to ticket_url(@ticket), notice: "ticket status was successfully updated." }
          format.json { render :show, status: :ok, location: @ticket }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      end

    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to created_tickets_path, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def users
    query = params[:query]
    users = User.where('email LIKE ?', "#{query}%")
    render json: { users: users }
  end

  def assigned
    @assigned_tickets = Ticket.where(assignee_id: current_user.id)
  end

  def created
    @created_tickets = Ticket.where(assigner_id: current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:title, :description, :priority, :status, :start_date, :end_date, :assigner_id, :assignee_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/core_helper.rb
module CoreHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/core/dashboard.html.erb
<%= render 'layouts/sidebar'%>
<div class="p-4 sm:ml-64">
   <div class="p-4 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700"> 
      <% if alert.present? %>
         <div class="bg-red-600 border-t-4 border-red-700 text-bold rounded-b text-blue-900 px-4 py-3 mb-4 text-center text-white" role="alert">
            <p><%= alert %></p>
         </div>
      <% end %>
      <a href="<%= new_ticket_path %>">
         <div class="flex items-center justify-center h-48 mb-4 rounded bg-gradient-to-br from-blue-300 to-blue-500 dark:from-blue-600 dark:to-blue-800 text-white cursor-pointer">
            <div class="text-center">
                  <svg class="w-12 h-12 mx-auto" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
                     <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 1v16M1 9h16"/>
                  </svg>
                  <p class="text-2xl font-semibold">Create New Ticket</p>
            </div>
         </div>
      </a>
      <div class="grid grid-cols-2 gap-4 mb-4">
         <div class="flex flex-col items-center justify-center p-4 rounded bg-blue-100 dark:bg-blue-800">
            <svg class="w-12 h-12 text-blue-500 dark:text-blue-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
               <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
            <p class="text-xl text-blue-600 dark:text-blue-400">New Tickets (<%= @new_count %>)</p>
         </div>
         <div class="flex flex-col items-center justify-center p-4 rounded bg-red-100 dark:bg-red-800">
            <svg class="w-12 h-12 text-red-500 dark:text-red-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
               <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16l-4-4m0 0l4-4m-4 4h18" />
            </svg>
            <p class="text-xl text-red-600 dark:text-red-400">In Progress (<%= @inprogress_count %>)</p>
         </div>
         <div class="flex flex-col items-center justify-center p-4 rounded bg-yellow-100 dark:bg-yellow-800">
            <svg class="w-12 h-12 text-yellow-500 dark:text-yellow-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
               <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8V4m0 0V4m0 4h4m-4 0H8m-4 0H4m0 4v4m0-4v4m0-4h4m-4 0H8" />
            </svg>
            <p class="text-xl text-yellow-600 dark:text-yellow-400">Pending (<%= @pending_count %>)</p>
         </div>
         <div class="flex flex-col items-center justify-center p-4 rounded bg-green-100 dark:bg-green-800">
            <svg class="w-12 h-12 text-green-500 dark:text-green-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
               <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
            </svg>
            <p class="text-xl text-green-600 dark:text-green-400">Completed (<%= @completed_count %>)</p>
         </div>
      </div>
   </div>
</div>

app/views/layouts/_sidebar.html.erb
<button data-drawer-target="cta-button-sidebar" data-drawer-toggle="cta-button-sidebar" aria-controls="cta-button-sidebar" type="button" class="inline-flex items-center p-2 mt-2 ml-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
  <span class="sr-only">Open sidebar</span>
  <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
    <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
  </svg>
</button>

<aside id="cta-button-sidebar" class="fixed left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0" aria-label="Sidebar">
   <div class="h-full px-3 py-4 overflow-y-auto bg-gray-50 dark:bg-gray-800">
      <a href="<%=dashboard_path%>" class="flex hover:bg-gray-50 hover:text-black items-center pl-2.5 mb-5">
         <img src="https://flowbite.com/docs/images/logo.svg" class="h-6 mr-3 sm:h-7" alt="Flowbite Logo" />
         <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Take Ease</span>
      </a>
      <ul class="space-y-2 font-medium">
         <li>
            <a href="<%= dashboard_path %>" class="flex items-center p-2 hover:text-black text-gray-900 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="w-5 h-5 text-gray-500 transition duration-75  group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 21">
                  <path d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z"/>
                  <path d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z"/>
               </svg>
               <span class="ml-3">Dashboard</span>
            </a>
         </li>
         <li>
            <a href="<%= assigned_tickets_path %>" class="flex items-center p-2 text-gray-900 rounded-lg hover:text-black dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                  <path d="m17.418 3.623-.018-.008a6.713 6.713 0 0 0-2.4-.569V2h1a1 1 0 1 0 0-2h-2a1 1 0 0 0-1 1v2H9.89A6.977 6.977 0 0 1 12 8v5h-2V8A5 5 0 1 0 0 8v6a1 1 0 0 0 1 1h8v4a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-4h6a1 1 0 0 0 1-1V8a5 5 0 0 0-2.582-4.377ZM6 12H4a1 1 0 0 1 0-2h2a1 1 0 0 1 0 2Z"/>
               </svg>
               <span class="flex-1 ml-3 whitespace-nowrap">Assigned</span>
            </a>
         </li>
         <li>
            <a href="<%= created_tickets_path %>" class="flex items-center p-2 text-gray-900 rounded-lg hover:text-black dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 18">
                  <path d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z"/>
               </svg>
               <span class="flex-1 ml-3 whitespace-nowrap">Created</span>
            </a>
         </li>
         <li>
            <a href="<%= calendar_path %>" class="flex items-center p-2 text-gray-900 rounded-lg hover:text-black dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
            <svg class="w-5 h-5 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
               <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1v3m5-3v3m5-3v3M1 7h18M5 11h10M2 3h16a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Z"/>
            </svg>
            <span class="flex-1 ml-3 whitespace-nowrap">Calendar View</span>
            </a>
        </li>
        <li>
            <a href="<%= edit_user_registration_path %>" class="flex items-center p-2 text-gray-900 rounded-lg hover:text-black dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
            <svg class="w-5 h-5 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
               <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1v3m5-3v3m5-3v3M1 7h7m1.506 3.429 2.065 2.065M19 7h-2M2 3h16a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Zm6 13H6v-2l5.227-5.292a1.46 1.46 0 0 1 2.065 2.065L8 16Z"/>
            </svg>
            <span class="flex-1 ml-3 whitespace-nowrap">Edit Profile</span>
            </a>
        </li>
         <li>
            <a href="<%= destroy_user_session_path%>" data-method="delete" class="flex items-center p-2 hover:text-black text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 16">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 8h11m0 0L8 4m4 4-4 4m4-11h3a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-3"/>
               </svg>
               <span class="flex-1 ml-3 whitespace-nowrap">Sign Out</span>
            </a>
         </li>
         
      </ul>
   </div>
</aside>

<script>
  let sidebarButton = document.querySelector('[data-drawer-toggle="cta-button-sidebar"]');
  let sidebar = document.querySelector('#cta-button-sidebar');

  sidebarButton.addEventListener('click', () => {
    sidebar.classList.toggle('-translate-x-full');
  });
</script>

app/views/tickets/assigned.html.erb
<% if notice.present? %>
  <div class="bg-blue-100 border-t-4 border-blue-500 rounded-b text-blue-900 px-4 py-3 mb-4 text-center" role="alert">
    <p><%= notice %></p>
  </div>
<% end %>


<%= render 'layouts/sidebar' %>

<div class="p-4 sm:ml-64">
  <div class="p-4 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700">

    <div class="container mx-auto mt-8">
      <h1 class="text-3xl font-bold mb-4">Assigned Tickets</h1>

      <section class="mb-8" id="assigned-tickets-section">
        <div class="overflow-x-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead>
              <tr>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Title</th>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Due Date</th>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Priority</th>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Status</th>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @assigned_tickets.each do |ticket| %>
                <tr class="bg-gray-200 border-b border-gray-300">
                
                  <td class="px-6 py-4 whitespace-nowrap underline cursor-pointer"><%= link_to ticket.title, ticket, class: "hover:text-black hover:bg-gray-200"%></td> 
                  <td class="px-6 py-4 whitespace-nowrap"><%= ticket.end_date %></td>
                  <td class="px-6 py-4 whitespace-nowrap
                    <%= ticket.priority == 'Urgent' ? 'text-red-600' :
                      (ticket.priority == 'Important' ? 'text-red-500' :
                        (ticket.priority == 'Moderate' ? 'text-yellow-500' : 'text-green-500')) %>">
                    <%= ticket.priority %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= ticket.status %></td>
                  <td class="px-6 py-4 whitespace-nowrap">

                    <%= link_to 'Edit Status', edit_ticket_path(ticket), class: 'text-green-600 hover:underline hover:text-black hover:bg-gray-200' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

      </section>
    </div>
  </div>
</div>

app/views/tickets/created.html.erb
<% if notice.present? %>
  <div class="bg-blue-100 border-t-4 border-blue-500 rounded-b text-blue-900 px-4 py-3 mb-4 text-center" role="alert">
    <p><%= notice %></p>
  </div>
<% end %>

<%= render 'layouts/sidebar'%>
<div class="p-4 sm:ml-64">
  <div class="p-4 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700">

    <div class="container mx-auto mt-8">
      <h1 class="text-3xl font-bold mb-4">Created Tickets</h1>
      <section id="created-tickets-section">
      <div class="overflow-x-auto">
        <table class="min-w-full divide-y divide-gray-200">
          <thead>
            <tr>
              <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Title</th>
              <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Due Date</th>
              <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Priority</th>
              <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Status</th>
              <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @created_tickets.each do |ticket| %>
              <tr class="bg-gray-200 border-b border-gray-300">
                <td class="px-6 py-4 whitespace-nowrap underline cursor-pointer"><%= link_to ticket.title, ticket, class: "hover:text-black hover:bg-gray-200"%></td> 
                <td class="px-6 py-4 whitespace-nowrap"><%= ticket.end_date %></td>
                <td class="px-6 py-4 whitespace-nowrap
              <%= ticket.priority == 'Urgent' ? 'text-red-600 ' :
                (ticket.priority == 'Important' ? 'text-red-500' :
                  (ticket.priority == 'Moderate' ? 'text-yellow-500' : 'text-green-500')) %>">
                  <%= ticket.priority %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap"><%= ticket.status %></td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <%= link_to 'Edit', edit_ticket_path(ticket), class: 'text-green-600 hover:underline' %>
                  <%= link_to 'Delete', ticket, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-red-600 hover:underline' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        </div>
        
      </section>
    </div>
    <div class="container mx-auto mt-8">
      <%= link_to 'New ticket', new_ticket_path, class: 'px-4 py-2 bg-blue-300 text-white hover:bg-blue-600 rounded-lg' %>
    </div>
  </div>
</div>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Priority</th>
      <th>Status</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Assigner</th>
      <th>Assignee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.title %></td>
        <td><%= ticket.description %></td>
        <td><%= ticket.priority %></td>
        <td><%= ticket.status %></td>
        <td><%= ticket.start_date %></td>
        <td><%= ticket.end_date %></td>
        <td><%= ticket.assigner_id %></td>
        <td><%= ticket.assignee_id %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<%= render 'layouts/sidebar' %>
<p id="notice"><%= notice %></p>
<div class="p-4 sm:ml-64">
  <div class="p-4 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700 transition-transform transform hover:scale-105">
    <div class="bg-white p-6 rounded-lg shadow-md">
      <h2 class="text-2xl font-semibold mb-4">Ticket Details</h2>
      <div class="grid grid-cols-1 gap-4">
        <div>
          <p class="text-gray-600 font-semibold">Title:</p>
          <p class="mb-4"><%= @ticket.title %></p>
        </div>
        <div>
          <p class="text-gray-600 font-semibold">Description:</p>
          <p class="mb-8"><%= @ticket.description %></p>
        </div>
      </div>
      <div class="grid grid-cols-2 gap-4">
        <div>
          <p class="text-gray-600 font-semibold">Start Date:</p>
          <p class="mb-4"><%= @ticket.start_date %></p>
        </div>
        <div>
          <p class="text-gray-600 font-semibold">End Date:</p>
          <p class="mb-4"><%= @ticket.end_date %></p>
        </div>
        <div>
          <p class="text-gray-600 font-semibold">Priority:</p>
          <p class="mb-4"><%= @ticket.priority %></p>
        </div>
        <div>
          <p class="text-gray-600 font-semibold">Status:</p>
          <p class="mb-4"><%= @ticket.status %></p>
        </div>
        <div>
          <p class="text-gray-600 font-semibold">Assigner:</p>
          <p class="mb-4"><%= @ticket.assigner.email %></p>
        </div>
        <div>
          <p class="text-gray-600 font-semibold">Assignee:</p>
          <p class="mb-4"><%= @ticket.assignee.email %></p>
        </div>
      </div>
      <div class="mt-6 flex justify-center">
        <%= link_to 'Edit', edit_ticket_path(@ticket), class: 'text-white mx-2 px-4 py-2 bg-blue-500 font-semibold rounded-full hover:bg-blue-600 transition duration-300 ease-in-out transform hover:scale-105' %>
      </div>
    </div>
  </div>
</div>